### ISSUE TITLE
Action Plan for 0.1.0

### ISSUE THREAD

**Issue by taras** [cowboyd/microstates.js#2]
# TODO
- [x] curry context into transitions (ie. first argument should be current value) #1 
- [x] partition transitions from other methods on MicroState #1 
- [x] eliminate `replace` operation for primitive micro states (replace with merge) #1 
- [x] make `replace` a transition #1 
- [x] add ability to run tests in the browser https://github.com/taras/microstates.js/pull/1
- [x] tests now run in node too
- [ ] Safari doesn't like `defineProperty(Class, 'name', {value: name });`
- [ ] Tests don't run in Phantom.js
- [ ] TodoItem MicroState
- [ ] Complete TodoItem creates new TodoList MicroState
- [ ] TodoItem must also operate in isolation

**Comment by taras** [comment]
I added a test to `object-test.js` that checks for correct behaviour with inheritance. The current implementation doesn't take parent's constructor if one was specified. We should probably grab Super's constructor on 3rd+ level inheritance when a custom constructor was specified on previous level.

```js
describe("inheritance", function(){
    let WorkTodoList;
    let workList;
    beforeEach(function(){
      WorkTodoList = TodoList.extend('WorkTodoList', {
        get upperName() {
          return `☭ ${this.name.toUpperCase()}`;
        },

        due: 'today',

        transitions: {
          changeDue(current, due) {
            return {
              due: due
            }
          }
        }
      });
      workList = new WorkTodoList('day job', ['write code', 'talk to client']);
    });
    it("maintains prototype chain", function(){
      expect(workList).to.be.instanceOf(TodoList);
      expect(workList).to.be.instanceOf(WorkTodoList);
      expect(workList.upperName).to.equal('☭ DAY JOB');
    });
  });
```
