### ISSUE TITLE
Roadmap For Reboot

### ISSUE THREAD

**Issue by cowboyd** [cowboyd/microstates.js#6]
## Order of operations
- [ ] create reboot branch, and reset the test suite to a simple mocha runner. #10 
- [ ] Find out a way to run tests in the browser, while still maintaining a simple build process, and sourcemaps. #10 
- [ ]  Opaque `State` whose only transition is `set()` #7 
- [ ] `Bool` state with `toggle()` #8 
- [ ] `Num` state with standard arithmetic operations #9
- [ ] `Record` state with an `assign` and `put` transitions (basically a microstate boxing JavaScript `Object`) #11 
- [ ] `List` state with standard list operations.
- [ ] Composable States
  - compose Map
  - compose List
- [ ] Parameterizable States.
- [ ] Multiple Select
- [ ] Overrideable Substates
- [ ] Single Select
